# NumPy

- **[NumPy Data Type](#NumPy-Data-Type)**
- **[NumPy Arrays](#NumPy-Arrays)**
- **[Ndarray Calculation](#Ndarray-Calculation)**
    - [.shape](#.shape)
    - [Indexing and Slicing](#Indexing-and-Slicing)
    - [np.arange(), np.linspace(), np.logspace()](#np.arange(),-np.linspace(),-np.logspace())
    - [np.zeros(), np.ones(), np.eye()](#np.zeros())
- **[np.random](#np.random)**
    - [np.random.rand()](#np.random.rand())
    - [np.random.randn()](#np.random.randn())
    - [np.random.randint()](#np.random.randint())
    - [np.random.choice()](#np.random.choice())
- **[Statistics](#Statistics)**
- **[Mathmatical Functions](#Mathmatical-Functions)**
    - [np.nan and np.isnan()](#np.nan-and-np.isnan())
- **[Other Functions](#Other-Functions)**
    - [np.clip()](#np.clip())
- **[NumPy Array Conditions](#NumPy-Array-Conditions)**
    - [np.where()](#np.where())
    - [np.unique()](#np.unique())
    - [np.bincount()](#np.bincount())
    - [np.concatenate() and np.stack()](#np.concatenate()-and-np.stack())
    - [np.transpose() or .T](#np.transpose()-or-.T)
- **[Save](#Save)**
    - [np.save() and np.load()](#np.save()-and-np.load())

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Data Type

■`int` (signed integer)

|data type|decription|
|:--|:--|
|`int8`|8 bits signed integer|
|`int16`|16 bits signed integer|
|`int32`|32 bits signed integer|
|`int64`|64 bits signed integer|

■`uint` (unsigned integer)

|data type|decription|
|:--|:--|
|`uint8`|8 bits signed integer|
|`uint16`|16 bits signed integer|
|`uint32`|32 bits signed integer|
|`uint64`|64 bits signed integer|

■`float` (floating point number)

|data type|decription|
|:--|:--|
|`float16`|16 bits signed integer|
|`float32`|32 bits signed integer|
|`float64`|64 bits signed integer|
|`float128`|128 bits signed integer|

■`bool` （True or False）

|data type|description|
|:--|:--|
|`bool`|`True` or `False`|

## NumPy Arrays

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [13]:
type(matrix[0][0])

numpy.complex128

In [14]:
type(1)

int

In [16]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [21]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)  # unsigned integer 8 bit 0~255
ndarray = np.array([1, 2, 3], dtype=np.float32)  # for data save for ML
ndarray = np.array([1, 2, 3], dtype=np.float64)  # for ML model learning

In [22]:
ndarray

array([1., 2., 3.])

## Ndarray Calculation

In [23]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [30]:
array1 + array2  # broadcasting: automatically filled out 

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [32]:
array3 + array1 

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [33]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# a = [1, 2, 3]
# a + 3  error in list

### .shape

In [39]:
array1 = np.array([1, 2])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
# array1 + array2 error in concatenate

In [46]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
ndarray.shape

(3, 2)

In [45]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [52]:
print(ndarray1)
print(ndarray2)

[1 2 3]
[[1 2 3]]


In [51]:
print(ndarray1.shape)
print(ndarray2.shape)

(3,)
(1, 3)


In [58]:
expand_ndarray = np.expand_dims(ndarray1, axis=-1)  # equal to ndarray2

In [59]:
expand_ndarray.shape

(3, 1)

In [62]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [64]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [65]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Indexing and Slicing 

In [66]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [67]:
ndarray[-1]

4

In [69]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
# ndarray[0][1]
ndarray[0, 1]

2

In [75]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [77]:
ndarray[1:3]


array([2, 3])

In [79]:
ndarray[:3]

array([1, 2, 3])

In [76]:
ndarray[1:]

array([2, 3, 4])

In [80]:
ndarray[:-2]

array([1, 2])

In [81]:
ndarray[:]

array([1, 2, 3, 4])

In [82]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 ,11, 12], [13, 14, 15, 16]])

In [83]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [87]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

### np.arange(), np.linspace(), np.logspace()

In [91]:
np.arange(10, 1, -1)  # start, stop, end

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [90]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [93]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [99]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

In [100]:
np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [103]:
10 ** np.linspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

### np.zeros()

In [106]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.zeros(3)

array([0., 0., 0.])

### np.ones()

In [108]:
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
np.ones(3)

array([1., 1., 1.])

In [110]:
np.ones((5, 4)) * 5 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

### np.eye()

In [111]:
# I: identify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.random 

### np.random.rand()

In [117]:
## pseudo random
np.random.rand(3, 4)

array([[0.45634713, 0.34009887, 0.89605553, 0.94202573],
       [0.15398775, 0.3315658 , 0.82808062, 0.75752012],
       [0.02080751, 0.07918502, 0.26046421, 0.68649694]])

### np.random.seed()

In [120]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [121]:
np.random.rand()

0.7203244934421581

### np.random.randn()

In [126]:
np.random.randn(3, 4)  # returnrandom values from standard normal distribution

array([[-2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918,  1.14472371,  0.90159072]])

In [129]:
np.random.normal(loc=10, scale=1)

9.316272140825667

### np.random.randint()

In [130]:
np.random.randint(10, 100, (2, 3))

array([[36, 35, 32],
       [19, 77, 33]])

In [131]:
np.random.randint(10)

4

### np.random.choice()

In [133]:
a = [1, 2, 3]
np.random.choice(a)

2

In [134]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [152]:
idx = np.random.choice(index_pool)
idx

8

## Statistics

In [153]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 0.34558368, -0.42551404, -2.23877138,  1.75539696, -0.26419336],
       [ 0.84629447,  2.0867325 ,  0.52647831,  0.983809  , -1.92220001],
       [-0.89482523,  0.33006282,  1.048591  ,  1.34989935,  1.24567511],
       [-0.69119147,  1.28107338, -0.72706431, -0.79916869, -0.00354562],
       [ 0.51259464, -0.16786086,  1.34633628, -0.61549198, -0.7430367 ]])

In [156]:
# maximum
std_norm.max()
# np.max(std_norm)

2.0867325009821442

In [158]:
# minumum
std_norm.min()
# np.min(std_norm)

-2.2387713760258197

In [162]:
# get index at the maximum/minimum
std_norm.argmax()
std_norm.argmin()

2

In [163]:
std_norm.flatten()[2]

-2.2387713760258197

In [165]:
# average
std_norm.mean()

0.1666265532288378

In [168]:
# median
#  xxx std_norm.median()
np.median(std_norm)

0.3300628215380945

In [174]:
# median vs average in time
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print(f"median took {after_median - before} sec")
print(f"mean took {after_mean - after_median} sec")

median took 0.016992568969726562 sec
mean took 0.0013260841369628906 sec


In [175]:
# standard deviation
np.std(std_norm)

1.0859850993884694

In [178]:
std_norm.max(axis=0)  # axis=0: w.r.t. column, axis=1: w.r.t. row

array([0.84629447, 2.0867325 , 1.34633628, 1.75539696, 1.24567511])

## Mathmatical Functions

In [179]:
# square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [181]:
# logarithm
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [183]:
# exponential function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [184]:
np.e

2.718281828459045

In [186]:
# summation
array = np.arange(1, 11)
np.sum(array)

55

In [187]:
ndarray = array.reshape(2, 5)
np.sum(ndarray, axis=1)

array([15, 40])

In [188]:
# absolute value
array = np.arange(-10, 0)
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### np.nan and np.isnan()

In [190]:
# NaN: Not a Number
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


nan

In [191]:
type(np.nan)

float

In [192]:
a = None
a is None

True

In [193]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [195]:
np.log(-100) == np.nan
np.log(-100) is np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


False

## Other Functions

### np.clip()

In [196]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

## NumPy Array Conditions

### np.where()

In [200]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [205]:
result, = np.where(array > 3)
result

array([4, 5, 6, 7, 8, 9])

In [203]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [204]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [207]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [210]:
# all true?
(ndarray > 3).all()

False

In [211]:
# any true?
(ndarray > 3).any()

True

In [213]:
(ndarray > 3).all(axis=1)

array([False,  True])

### np.unique()

In [215]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [216]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [217]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

### np.bincount()

In [220]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

### np.concatenate() and np.stack()

In [221]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [223]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [228]:
np.concatenate([ndarray_even, ndarray_odd], axis=0)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [244]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [245]:
stacked_array = _

In [246]:
stacked_array.shape

(3, 3, 2)

### np.transpose() or .T

In [247]:
ndarray = np.random.randn(3, 4)
ndarray

array([[-0.13205368, -0.30032212,  1.42097993, -1.78615591],
       [-0.1153204 , -0.35450565,  1.48517756, -0.41423655],
       [-0.86265006,  0.61129059, -1.60534602, -0.20473899]])

In [248]:
ndarray.shape

(3, 4)

In [249]:
np.transpose(ndarray)

array([[-0.13205368, -0.1153204 , -0.86265006],
       [-0.30032212, -0.35450565,  0.61129059],
       [ 1.42097993,  1.48517756, -1.60534602],
       [-1.78615591, -0.41423655, -0.20473899]])

In [250]:
transposed_ndarray = _

In [251]:
transposed_ndarray.shape

(4, 3)

In [252]:
ndarray.T

array([[-0.13205368, -0.1153204 , -0.86265006],
       [-0.30032212, -0.35450565,  0.61129059],
       [ 1.42097993,  1.48517756, -1.60534602],
       [-1.78615591, -0.41423655, -0.20473899]])

In [253]:
ndarray = np.random.randn(3, 4, 5)

In [254]:
ndarray.T.shape

(5, 4, 3)

## Save

### np.save() and np.load()

In [255]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [256]:
np.save('sample_ndarray', ndarray)

In [258]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [259]:
dictionary = {
    'id': 123456,
    'image': ndarray
}

In [261]:
np.save('sample_dict.npy', dictionary)

In [267]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)[()]

In [268]:
type(loaded_dict)

dict

In [265]:
a = np.array({'a': 1})

In [266]:
a[()]

{'a': 1}